language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install g++
  - sudo apt-get install cmake
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake -DBUILD_TEST=ON ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./belledonne/tests/belledonne_tests
